table DIM_DATE
	lineageTag: f48efbc8-1668-4ded-bb40-0cf1dd4d5fb1
	dataCategory: Time

	column DATE
		dataType: dateTime
		isKey
		formatString: Long Date
		lineageTag: 79643d50-63bf-4f2f-9ffb-9ff8da30da63
		summarizeBy: none
		sourceColumn: DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column YEAR
		dataType: int64
		formatString: 0
		lineageTag: 45f9f93e-ead7-421a-980e-0ab4b2eb3ca6
		summarizeBy: sum
		sourceColumn: YEAR

		annotation SummarizationSetBy = Automatic

	column QUARTER
		dataType: int64
		formatString: 0
		lineageTag: 20d93eb0-99c6-4831-a09b-5c5acebd2b4f
		summarizeBy: sum
		sourceColumn: QUARTER

		annotation SummarizationSetBy = Automatic

	column MONTH
		dataType: int64
		formatString: 0
		lineageTag: 7dd0b74f-5bbd-4a95-86b1-c765fd7cf4e0
		summarizeBy: sum
		sourceColumn: MONTH

		annotation SummarizationSetBy = Automatic

	column MONTH_NAME
		dataType: string
		lineageTag: 4a6344b9-da62-49b0-be2f-d3b3847f19fc
		summarizeBy: none
		sourceColumn: MONTH_NAME

		annotation SummarizationSetBy = Automatic

	column DAY_OF_MONTH
		dataType: int64
		formatString: 0
		lineageTag: 23bea72b-d866-47f6-bca7-25ab1304680d
		summarizeBy: sum
		sourceColumn: DAY_OF_MONTH

		annotation SummarizationSetBy = Automatic

	column DAY_OF_WEEK
		dataType: int64
		formatString: 0
		lineageTag: fc691874-fdf2-4634-ae7f-b6eab5b3023c
		summarizeBy: sum
		sourceColumn: DAY_OF_WEEK

		annotation SummarizationSetBy = Automatic

	column WEEK_OF_YEAR
		dataType: int64
		formatString: 0
		lineageTag: 60b066ac-b10b-4733-b5a4-8dfce49c15ad
		summarizeBy: sum
		sourceColumn: WEEK_OF_YEAR

		annotation SummarizationSetBy = Automatic

	column DAY_OF_YEAR
		dataType: int64
		formatString: 0
		lineageTag: c1aaac0d-fafb-4372-a0db-d23ca6d304e8
		summarizeBy: sum
		sourceColumn: DAY_OF_YEAR

		annotation SummarizationSetBy = Automatic

	column DAY_NAME
		dataType: string
		lineageTag: 10c15164-6150-444e-8e96-1fb723b4297c
		summarizeBy: none
		sourceColumn: DAY_NAME

		annotation SummarizationSetBy = Automatic

	column WEEK_PART
		dataType: string
		lineageTag: 5c611275-114c-44bb-8bf8-3aea753c0836
		summarizeBy: none
		sourceColumn: WEEK_PART

		annotation SummarizationSetBy = Automatic

	column DAY_NUMBER
		dataType: int64
		formatString: 0
		lineageTag: c2a0e0cb-c441-4d84-a242-8836f78b369c
		summarizeBy: sum
		sourceColumn: DAY_NUMBER

		annotation SummarizationSetBy = Automatic

	column YEAR_NUMBER
		dataType: int64
		formatString: 0
		lineageTag: dec7a6fb-5f6b-4b92-89cc-2b614cd186c1
		summarizeBy: sum
		sourceColumn: YEAR_NUMBER

		annotation SummarizationSetBy = Automatic

	column QUARTER_NUMBER
		dataType: int64
		formatString: 0
		lineageTag: 7578ad74-430d-4984-a7e4-4cc342fdd88f
		summarizeBy: sum
		sourceColumn: QUARTER_NUMBER

		annotation SummarizationSetBy = Automatic

	column MONTH_NUMBER
		dataType: int64
		formatString: 0
		lineageTag: e18a51ac-4794-4980-8748-11b6e6dea6b1
		summarizeBy: sum
		sourceColumn: MONTH_NUMBER

		annotation SummarizationSetBy = Automatic

	column YEAR_QUARTER
		dataType: string
		lineageTag: bd10c4b4-68fd-411a-a281-d4d506c9c3e3
		summarizeBy: none
		sourceColumn: YEAR_QUARTER

		annotation SummarizationSetBy = Automatic

	column YEAR_MONTH
		dataType: string
		lineageTag: 79262f6a-70c6-4ba2-9c49-0802c2862760
		summarizeBy: none
		sourceColumn: YEAR_MONTH

		annotation SummarizationSetBy = Automatic

	column WEEK_START_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 70838657-fa9d-4430-b870-9f0d5933bc05
		summarizeBy: none
		sourceColumn: WEEK_START_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MONTH_START_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: e3559919-faad-49a4-bbc8-22745ee0e91a
		summarizeBy: none
		sourceColumn: MONTH_START_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column QUARTER_START_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 50eebbe4-dee3-45fc-b40a-2c269da4a380
		summarizeBy: none
		sourceColumn: QUARTER_START_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column YEAR_START_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6dce7d12-8672-4de4-a8ed-f58d0b2739ca
		summarizeBy: none
		sourceColumn: YEAR_START_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column FINANCIAL_YEAR
		dataType: int64
		formatString: 0
		lineageTag: d5c216f2-1d5d-4ad6-a961-4d7fb1243c2d
		summarizeBy: sum
		sourceColumn: FINANCIAL_YEAR

		annotation SummarizationSetBy = Automatic

	column FINANCIAL_QUARTER
		dataType: int64
		formatString: 0
		lineageTag: 48b7ae72-2663-4696-a5ae-369f6653539e
		summarizeBy: sum
		sourceColumn: FINANCIAL_QUARTER

		annotation SummarizationSetBy = Automatic

	column FINANCIAL_MONTH
		dataType: int64
		formatString: 0
		lineageTag: 9502023f-8f70-4c17-96d5-a8d93f610069
		summarizeBy: sum
		sourceColumn: FINANCIAL_MONTH

		annotation SummarizationSetBy = Automatic

	column FINANCIAL_WEEK
		dataType: int64
		formatString: 0
		lineageTag: 022f282e-6ba7-49a4-bd40-d3cff80b85be
		summarizeBy: sum
		sourceColumn: FINANCIAL_WEEK

		annotation SummarizationSetBy = Automatic

	column FINANCIAL_DAY
		dataType: int64
		formatString: 0
		lineageTag: 9dee4060-e229-44f1-bd16-6fb2ec5cb0a9
		summarizeBy: sum
		sourceColumn: FINANCIAL_DAY

		annotation SummarizationSetBy = Automatic

	column HOLIDAY_NAME
		dataType: string
		lineageTag: e1233228-018b-4a71-a3db-2126de533737
		summarizeBy: none
		sourceColumn: HOLIDAY_NAME

		annotation SummarizationSetBy = Automatic

	column HOLIDAY
		dataType: string
		lineageTag: a955ab3f-a393-4e71-8289-83b77ce4dabf
		summarizeBy: none
		sourceColumn: HOLIDAY

		annotation SummarizationSetBy = Automatic

	partition DIM_DATE = m
		mode: import
		source =
				let
				    Source = Value.NativeQuery(Snowflake.Databases("gp81875.west-europe.azure.snowflakecomputing.com","DATA_SCIENCE",[Role="DATA_SCIENTIST"]){[Name="LUMILINKS"]}[Data], "SELECT * FROM#(lf)LUMILINKS.CORE.DIM_DATE", null, [EnableFolding=true]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"YEAR", Int64.Type}, {"QUARTER", Int64.Type}, {"MONTH", Int64.Type}, {"DAY_OF_MONTH", Int64.Type}, {"DAY_OF_WEEK", Int64.Type}, {"WEEK_OF_YEAR", Int64.Type}, {"DAY_OF_YEAR", Int64.Type}, {"DAY_NUMBER", Int64.Type}, {"YEAR_NUMBER", Int64.Type}, {"QUARTER_NUMBER", Int64.Type}, {"MONTH_NUMBER", Int64.Type}, {"FINANCIAL_YEAR", Int64.Type}, {"FINANCIAL_QUARTER", Int64.Type}, {"FINANCIAL_MONTH", Int64.Type}, {"FINANCIAL_WEEK", Int64.Type}, {"FINANCIAL_DAY", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

